spring.application.name=Steganography

spring.mongodb.uri=${MONGODB_URI}

spring.devtools.restart.enabled=false
management.endpoints.web.exposure.include=health
spring.main.allow-bean-definition-overriding=true
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
mail.from=${MAIL_FROM}
spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}


spring.data.mongodb.auto-index-creation=true

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=always

server.port=${PORT:8080}