spring.application.name=Steganography

spring.data.mongodb.uri=mongodb+srv://Devina:asdfghjkl@learning.10ldmzq.mongodb.net/Steganography

spring.devtools.restart.enabled=false
management.endpoints.web.exposure.include=health
spring.main.allow-bean-definition-overriding=true
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}


spring.data.mongodb.auto-index-creation=true

server.port=${PORT:8080}
